export const PII_PATTERNS: { name: string; regex: RegExp }[] = [
  { name: "credit_card", regex: /\b\d{4}[\s-]?\d{4}[\s-]?\d{4}[\s-]?\d{4}\b/g },
  { name: "credit_card_nosep", regex: /\d{4}\d{4}\d{4}\d{4}/g },
  { name: "amex", regex: /\b3[47]\d{2}[\s-]?\d{6}[\s-]?\d{5}\b/g },
  { name: "amex_nosep", regex: /3[47]\d{2}\d{6}\d{5}/g },
  { name: "diners", regex: /\b3[068]\d{2}[\s-]?\d{6}[\s-]?\d{4}\b/g },
  { name: "diners_nosep", regex: /3[068]\d{2}\d{6}\d{4}/g },
  { name: "ssn", regex: /\b\d{3}-\d{2}-\d{4}\b/g },
  { name: "api_key_google", regex: /AIza[0-9A-Za-z_-]{35}/g },
  { name: "api_key_openai", regex: /sk-[a-zA-Z0-9_-]{20,}/g },
  { name: "api_key_sk_prefix", regex: /sk_[a-zA-Z0-9_]{20,}/g },
  { name: "bearer_token", regex: /Bearer\s+[a-zA-Z0-9._-]{20,}/g },
  { name: "private_key", regex: /-----BEGIN[A-Z ]*PRIVATE KEY-----/g },
  { name: "aws_key", regex: /AKIA[0-9A-Z]{16}/g },
  { name: "generic_secret", regex: /(?:secret|token|key|password|passwd|api_key)\s*[:=]\s*['"]?[^\s'"]{8,}/gi },
];
